8 main forum page
star-wars-kittens/The-star-wars-game pull request #13
Opened 2023-02-23 15:29 UTC by Bluorenge

### Какую задачу решаем
https://linear.app/star-wars-kittens/issue/STA-43/verstka-stranicy-foruma

### Скриншоты/видяшка (если есть)
![Star Wars - Google Chrome 2023-02-23 16 13 43](https://user-images.githubusercontent.com/16067434/220919233-01a5fd71-e4a7-4051-adef-aeab2f215076.png)

### TBD (если есть)

2023-02-25 12:47 UTC, stvdent47 commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +const { Title, Text } = Typography;
нужно обсудить, как работаем с ```Text/Title```, в других местах мы использовали ```<Typography.Text>```, здесь выходит по-другому. наверно стоит придерживаться одного стиля

2023-02-25 12:50 UTC, stvdent47 commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +export const AddTopicModal: React.FC<AddTopicModalProps> = ({
предлагаю назвать компонент ```ForumAddTopicModal```, чтобы было понятно, что это модалка для форума и без контекста

2023-02-25 13:01 UTC, stvdent47 requested changes

2023-02-25 13:01 UTC, stvdent47 commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +      });
после успешного создания топика, думаю, стоит показывать оповещение-всплывашку об успешном создании, как для успешной регистрации

2023-02-25 13:01 UTC, stvdent47 commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +      setAddTopicErrorText('Произошла ошибка при создании темы');
для ошибки тоже предлагаю использовать всплывашку

2023-02-25 13:01 UTC, stvdent47 commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +          Добавление новой темы для форума "{selectedForum?.title}"
мне кажется, тут и ниже стоит использовать константы для текста

2023-02-25 13:01 UTC, stvdent47 commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +        <Input placeholder="Введите название темы"></Input>
можно использовать ```<Input />```, если нечего положить внутрь + в других местах используем именно так

2023-02-25 13:01 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +    style={{
инлайновые стили — плохая практика, думаю, стоит вынести в класс

2023-02-25 13:01 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +      <Title style={{ marginTop: 0 }}>Форум</Title>
думаю, что и тут стоит использовать константы

2023-02-25 13:01 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +      <AddTopicModal
в ```ProfileForm``` я использовал модалку немного по-другому. в том случае приходится прокидывать меньше пропсов для управления.
мой поинт в том, что там сделано в одном стиле, тут в другом, нужно поменять либо здесь, либо там, иначе получается каша

2023-02-25 14:54 UTC, Bluorenge commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +      setAddTopicErrorText('Произошла ошибка при создании темы');
всплывашку - в смысле вот такую? https://ant.design/components/notification

2023-02-25 14:56 UTC, Bluorenge commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +      setAddTopicErrorText('Произошла ошибка при создании темы');
а, как в регистрации. всё, увидел

2023-02-25 16:00 UTC, stvdent47 commented on packages/client/src/components/Forum/AddTopicModal/AddTopicModal.tsx
> +      setAddTopicErrorText('Произошла ошибка при создании темы');
я использовал https://ant.design/components/message

2023-02-26 12:41 UTC, Bluorenge commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +      <AddTopicModal
Лучше поменять в том месте, потому что у меня логика показа сообщений завязана на отображении модалки - компонент сообщения находится внутри модалки. Тем более ты же в ту модалку тоже передаешь пропс open.

2023-02-26 18:48 UTC, stvdent47 commented on packages/client/src/components/Profile/ProfileForm/ProfileForm.tsx
> +      <Modal
когда я предлагал переделать модалку в компоненте `ForumMainPage` или здесь, я имел в виду сделать компонент, который вложить в модалку:
`<Modal>
  <ForumAddTopicModal>
</Modal>
`
а не убрать условное отображение модалки. при таком коде, раз открыв модалку, она останется висеть в доме, даже если ты ее закроешь. склоняюсь к тому, что убирать из дома все неиспользуемое (в разумных пределах) — норм практика

2023-02-26 18:48 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +const plusCircleOutlinedIcon = (
как-то пропустил, а какой смысл у этой переменной? она же просто кидается в прос? почему не кинуть в пропс сразу компонент?

2023-02-26 18:48 UTC, stvdent47 commented on packages/client/src/components/Forum/ForumAddTopicModal/ForumAddTopicModal.tsx
> +        <Typography.Title level={3} className="mt-2_5 mb-5">
не уверен насчет такого использования классов, мы это не обсудили, но опять получается каша.
я по привычке использовал бэм, у тебя получается что-то вроде велосипеда tailwind.
плюс используются разные значения: px/rem

2023-02-26 18:48 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +  const [isForumAddTopicModalOpen, setisForumAddTopicModalOpen] =
некритично, но, скорее всего, ты тут пропустил большую букву i `setIsForumAddTopicModalOpen`

2023-02-26 18:48 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +    <div className="forumPage">
наверно нужна какая-нибудь кнопка навигации: типа назад

вообще нам бы нужен навбар, но это другая задача

2023-02-27 17:14 UTC, Bluorenge commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +const plusCircleOutlinedIcon = (
когда инлайновые стили убраны да, смысла нет)

2023-02-27 17:15 UTC, Bluorenge commented on packages/client/src/components/Forum/ForumAddTopicModal/ForumAddTopicModal.tsx
> +        <Typography.Title level={3} className="mt-2_5 mb-5">
Да, это велосипед теилвинда - не охота класс ради одного стиля заводить. Оке, бэм сделаю

2023-02-27 17:17 UTC, Bluorenge commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +  const [isForumAddTopicModalOpen, setisForumAddTopicModalOpen] =
Да. Автозаменой поменялся регистр. Не заметил

2023-02-27 17:18 UTC, Bluorenge commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +    <div className="forumPage">
это обсудить надо

2023-02-27 17:45 UTC, Bluorenge commented on packages/client/src/components/Profile/ProfileForm/ProfileForm.tsx
> +      <Modal
Не вижу проблем с модалкой в доме.

И не понял всё-таки логику... Типа саму модалку создавать на странице, а внутрь передавать (в данном случае) инпут? Но тогда логику обработки ошибки/успеха нужно переносить в компонент страницы.

А хочется логику раздробить, поэтому и завел отдельный компонент модалки.
И ещё, в связи с этим условное отображением на странице форума не получится, потому что создание сообщения об успехе находится внутри компонента модалки. Соответственно, если по условию отрисовывать её, то сообщение об успехе будет пропадать, потому что при успехе модалка закрывается.

2023-02-27 18:11 UTC, stvdent47 commented on packages/client/src/components/Forum/ForumAddTopicModal/ForumAddTopicModal.tsx
> +        <Typography.Title level={3} className="mt-2_5 mb-5">
ну мы можем обсудить это, если созвонимся когда-нибудь, и, если договоримся, можем и такие заиспользовать, но, наверно, лучше с пикселями

2023-02-28 08:55 UTC, Bluorenge commented on packages/client/src/components/Forum/ForumAddTopicModal/ForumAddTopicModal.tsx
> +        <Typography.Title level={3} className="mt-2_5 mb-5">
Пока не обсудили, пусть бэм везде будет

2023-03-03 15:06 UTC, stvdent47 approved these changes

2023-03-03 15:06 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.tsx
> +  const [isForumAddTopicModalOpen, setisForumAddTopicModalOpen] =
дак, а чего сейчас не заменил?)

2023-03-03 15:06 UTC, stvdent47 commented on packages/client/src/pages/ForumMainPage/ForumMainPage.scss
> +@import 'core/utils';
импорт несуществующего файла, проект не запускается/собирается

2023-03-03 15:06 UTC, stvdent47 commented on packages/client/src/components/Profile/ProfileForm/ProfileForm.tsx
> +      <Modal
да, я потом понял, что в модалке по сути один инпут и сабмит висит по сути на компоненте модалки, а не на форме. наверно в этом конкретном случае и правда лучше вынести в отдельный компонент.
понял про сообщение.

2023-03-03 15:06 UTC, stvdent47 commented on packages/client/src/components/Forum/ForumAddTopicModal/ForumAddTopicModal.tsx
> +    setIsAddTopicLoading(false);
сейчас заметил
введенный текст в инпут после сабмита или отмены остается в инпуте, наверно, стоит очищать его

2023-03-03 15:10 UTC, stvdent47 commented
возможно, стоит очищать инпут и при отмене тоже.
или, если мы все же хотим его сохранить, хранить введенные значения для каждого отдельного топика.
потому что сейчас получается так, что можно ввести что-то в модалке для добавления трэда в один топик, отменить, начать создание для другого, а старый инпут останется

2023-03-03 22:48 UTC, practicum-maxim-zyryanov approved these changes

2023-03-06 09:46 UTC, merged