#1 add start setup of project
star-wars-kittens/The-star-wars-game pull request #2
Opened 2023-02-05 20:12 UTC by podolskijspace

### Сделал начальный конфиг проекта

2023-02-06 18:14 UTC, stvdent47 requested changes
помимо комментов в самом коде:
предлагаю добавить .npmrc для фиксированных версий пакетов
предлагаю добавить сокращения для путей, чтобы не делать ../../../../
мне кажется, файлы для экспорта компонентов нет смысла называть .tsx, для них достаточно .ts
мне кажется, нет смысла делать дефолтный экспорт для компонентов, потому что только добавляет работы при импорте писать вручную, хотя тут может я не знаю каких-то плюшек дефолтного экспорта
папки Components, Router и Pages предлагаю назвать тоже с маленькой буквы, чтобы все было консистентно
тесты падают

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/App.test.tsx
> +// import App from './App'
давайте удалять пустые файлы

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/App.tsx
> +import './App.scss'
компонент `App` наверно тоже стоит в отдельную папку сложить

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/App.tsx
> +import './App.scss'
стили мне кажется всегда импортируют в последнюю очередь

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/App.tsx
>  function App() {
`Layout` компонент сделан через `const`, этот `function`, наверно, стоит сделать одинаково
лично я за `const`

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/Components/Layout/Layout.tsx
> +const links = [
мне кажется, лучше это хранить в отдельном файле в `constants`, облегчит чтение

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/Pages/AuthPage/AuthPage.tsx
> +    <div>
зачем `div`?

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/core/Router/index.tsx
> +export {Router as default} from './Router';
почему именно дефолтный экспорт?

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/package.json
>    "devDependencies": {
мне кажется пакет antd, axios, react-router-dom, sass нужно в обычные зависимости перетащить

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/Components/Layout/Layout.tsx
> +import { Link } from 'react-router-dom'
я бы перенес в отдельную папку `src/layouts/` вряд ли в нашем проекте там будет лежать что-то еще, но все же это не компонент

2023-02-06 18:14 UTC, stvdent47 commented on packages/client/src/constants/routes.ts
> +export const MAIN_PAGE_PATH = '/'
предлагаю сделать пути объектом и экспортировать его, так не придется импортировать его потом через `import * as ROUTES from '../../constants/routes'`

2023-02-07 16:26 UTC, podolskijspace commented on packages/client/src/App.test.tsx
> +// import App from './App'
Удалил

2023-02-07 16:31 UTC, podolskijspace commented on packages/client/src/App.tsx
> +import './App.scss'
Решил, надо будет настроить, чтобы претиер формировал порядок импортов тоже

2023-02-07 16:32 UTC, podolskijspace commented on packages/client/src/App.tsx
>  function App() {
Да, через конст отлично будет

2023-02-07 16:32 UTC, podolskijspace commented on packages/client/src/Components/Layout/Layout.tsx
> +const links = [
Нет, потому что будут ситуации, когда мы будем импортить только один путь

2023-02-07 16:32 UTC, podolskijspace commented on packages/client/src/Pages/AuthPage/AuthPage.tsx
> +    <div>
Да просто так, базовая разметка, делай, как удобно

2023-02-07 16:38 UTC, podolskijspace commented on packages/client/src/Components/Layout/Layout.tsx
> +import { Link } from 'react-router-dom'
В будущем я его рассматриваю немного по-другому. Что это будет базовый компонент для публичных страниц, в котором будет какой-то хедр, может или что-то вроде того, сейчас большого значения не имеет, если он не будет нужным удалим. Отдельные папки тоже нет смысла плодить, есть папка компонентс, где переиспользующиеся компоненты, есть папка pages, в ней будут компоненты, которые используются только на этой странице

2023-02-07 16:38 UTC, podolskijspace commented on packages/client/package.json
>    "devDependencies": {
Нет смысла, сборщик умный и сам поймет на этапе билда. По-хорошему, можно все зависимости вставлять в дев. Но можно похоливарить эту тему

2023-02-07 16:38 UTC, podolskijspace commented on packages/client/src/core/Router/index.tsx
> +export {Router as default} from './Router';
Объяснений нет, это привычка. Есть папка, в которой хранится индексный файл с единственным дефолтным импортом.

2023-02-07 16:39 UTC, podolskijspace commented on packages/client/src/constants/routes.ts
> +export const MAIN_PAGE_PATH = '/'
Когда будут приватные и публичные роуты я это немного переработаю возможно, пока смысла нет, используется в 2 местах и не в окончательном виде

2023-02-07 16:43 UTC, podolskijspace commented
Сделал папки с маленькой буквы, согласен. 
Не понял, почему писать дефолтный экспорт больше работы? Если речь в целом не делать index файл, то в этом есть смысл, я опишу его. 
Алиасы хотел добавить, сразу не получилось, попробую еще. 
`.npmrc` добавил.
`ts` файлы нельзя называть, потому что тс умный и знает, если `ts` то внутри не может быть `jsx`. Попробуй проверить у себя где-нибудь.

2023-02-07 16:45 UTC, podolskijspace commented
Есть идеи, почему тест не проходит?

2023-02-07 21:59 UTC, stvdent47 commented on packages/client/src/constants/routes.ts
> +export const MAIN_PAGE_PATH = '/'
не уверен, что оставлять на потом хорошая практика, особенно, если это что-то несложное

2023-02-07 22:06 UTC, stvdent47 commented on packages/client/src/Components/Layout/Layout.tsx
> +const links = [
не совсем понял, что ты имеешь в виду
зачем `links` хранить имеено в файле компонента? это скорее имеет отношение к роутеру

2023-02-07 22:12 UTC, stvdent47 commented
> Не понял, почему писать дефолтный экспорт больше работы? Если речь в целом не делать index файл, то в этом есть смысл, я опишу его.
при импорте пишешь вручную название импортируемого компонента/функции/etc.

> .npmrc добавил.
нужно добавить `save-exact=true`, чтобы зависимости устанавливались точные без `^`

> ts файлы нельзя называть, потому что тс умный и знает, если ts то внутри не может быть jsx. Попробуй проверить у себя где-нибудь.
я говорю про то, что нужно файлы с реакт-компонентами называть `.tsx`, а файлы для экспорта `index.ts`, потому что в них будет только экспорт, не будет реакт-компонентов

2023-02-07 22:22 UTC, stvdent47 commented on packages/client/src/Components/Layout/Layout.tsx
> +import { Link } from 'react-router-dom'
думаю, что сейчас стоит многие вещи обсуждать с командой, а не единолично принимать решения.
это все же не исключительно твой проект, с которым мы тебе помогаем, как джуны, которые ничего не знают.
`Layout` — это все же не реакт-компонент в стандартном его понимании типа формы или блока и не страница, это просто другой тип реакт-компонента, поэтому я считаю, что нужно выделить в отдельную папку.

2023-02-07 22:26 UTC, stvdent47 commented on packages/client/vite.config.ts
> +      HOC: path.join(__dirname, './src/HOC'),
не уверен, нужен ли капс

2023-02-08 16:45 UTC, podolskijspace commented on packages/client/src/constants/routes.ts
> +export const MAIN_PAGE_PATH = '/'
Я это сделаю, когда буду делать приватные и публичные роуты, для этого нужна авторизация

2023-02-08 16:46 UTC, podolskijspace commented on packages/client/src/Components/Layout/Layout.tsx
> +import { Link } from 'react-router-dom'
Хорошо, можешь в своих issue так сделать, если считаешь так правильно делать

2023-02-08 16:49 UTC, podolskijspace commented on packages/client/src/Components/Layout/Layout.tsx
> +const links = [
Папка константы создана для переиспользующихся элементов. Здесь список специально для навигационного компонента, который будет использоваться в 1 компоненте. Если есть желание, можем вынести на общее обсуждение

2023-02-08 17:07 UTC, practicum-maxim-zyryanov requested changes
Ничего критичного, особенно для сетапа проекта, хотя признаюсь видна попытка сразу и авторизацию немного поделать и задачу с роутами порешать, что следовало бы делать в отдельных тасках, но в рамках начального сетапа на всё это готов закрыть глаза, главное прохождение тестов линтера исправить

2023-02-08 17:07 UTC, practicum-maxim-zyryanov commented on packages/client/vite.config.ts
> +      HOC: path.join(__dirname, './src/HOC'),
соглашусь

2023-02-08 17:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/App/App.test.tsx
> +})
Зачем нам нужен этот тест?

2023-02-08 17:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/Layout/Layout.tsx
> +        </Row>
Идея обобщить мне нравится, но возможно от него предстоит отказаться после внедрения приватных роутов... но как оно реально эволюционирует в дальнейшем узнаем вне рамок этого ревью :)

2023-02-08 17:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/constants/routes.ts
> +export const MAIN_PAGE_PATH = '/'
оставлять на потом действительно практика не очень, поправить легко, поэтому за то, чтобы поправить сразу

2023-02-08 17:08 UTC, practicum-maxim-zyryanov approved these changes

2023-02-08 17:23 UTC, stvdent47 approved these changes

2023-02-08 17:34 UTC, podolskijspace commented on packages/client/src/core/App/App.test.tsx
> +})
Потому что без тестов не проходит проверку

2023-02-08 17:35 UTC, podolskijspace commented on packages/client/src/components/Layout/Layout.tsx
> +        </Row>
Это чтобы показать роуты, возможно, это будет навигация по публичным роутам, возможно уйдёт

2023-02-08 19:27 UTC, merged