11 protected routes
star-wars-kittens/The-star-wars-game pull request #23
Opened 2023-03-07 09:27 UTC by Bluorenge

### Какую задачу решаем
Проверяем авторизацию пользователя при навигации по приложению.
Делаем редирект на предыдущую страницу с логина и регистрации, если пользователь авторизован.
Делаем редирект на логин с приватных страниц, если пользователь не авторизован.
При сабмите логина, делаем редирект на страницу, с которой редиректнулись на логин.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-10 23:49 UTC, practicum-maxim-zyryanov approved these changes

2023-03-11 19:27 UTC, stvdent47 reviewed
так как я меняю команду, не думаю, что имею право аппрувить или отклонять ПР.
лично у меня после того, как я забрал новую ветку, ничего не работает, это из-за того, что твой девелоп отличался на момент создания ПРа от актуального девелопа
если пофиксить эту проблему, то компонент защищенного роута не работает, я написал комменты к коду

2023-03-11 19:27 UTC, stvdent47 commented on packages/client/src/core/Router/Router.tsx
> -        path: ROUTES.MAIN_PAGE_PATH,
не очень понимаю, что происходит, но выглядит так, что у тебя были конфликты (из-за старой версии ветки develop, потому что ты начал делать задачу раньше меня), ты их не порешал и не ребейснул девелоп, а переписал изменения из одной (из нового develop) из моих предыдущих задач (я делал навбар, теперь из-за этих изменений его нет, тут можно сравнить текущий develop и эту ветку) на свою (старую версию файла)

2023-03-11 19:27 UTC, stvdent47 commented on packages/client/src/helpers/checkAuthLoader.ts
> +  return null;
возможно стоит возвращать не `null`, а спиннер, иначе пользователю будет казаться, что ничего не происходит, когда на самом деле идет загрузка

2023-03-11 19:27 UTC, stvdent47 commented on packages/client/src/helpers/checkAuthLoader.ts
> +  const currentUser = localStorage.getItem(LOCAL_STORAGE_IS_AUTH_KEY);
тут в `localStorage` храниться не пользователь, а флаг залогинен ли пользователь, так что название переменной может ввести в заблуждение. возможно, стоит выбрать что-то типа `isAuth` или `isLoggedIn`

2023-03-11 19:27 UTC, stvdent47 commented on packages/client/src/components/Login/Login.tsx
> +  const redirectTo = location.state?.from?.pathname || routes.MAIN_PAGE_PATH;
получатеся, что если я, будучи залогиненным попытаюсь зайти на логин, меня перебросит на страницу, на которой я был? может было бы логично перебрасывать на главную? (мне кажется, обычно так делают), но это просто вопрос, вам лучше его обсудить

2023-03-11 19:27 UTC, stvdent47 commented on packages/client/src/core/Router/ProtectedRouteWrap.tsx
> +  }, []);
сейчас эта фича не работает: можно попробовать, будучи залогиненным, набрать роут логина, и тебя с него не перебросит на главную, хотя должно, а ты попадешь на страницу логина.
так происходит, потому что при первом рендере `currentUser === null`: запрос запроса в бэк еще не было, не пришел ответ, не обновился `store`.
так что не хватает зависимости `currentUser`, без нее эта фича просто не работает.

2023-03-13 10:42 UTC, practicum-maxim-zyryanov requested changes
Считаю важным отработать оставленные комментарии и перепроверить работоспособность версии и поправить конфликты

2023-03-13 13:07 UTC, bondarevalexur commented on packages/client/src/components/Login/Login.tsx
> +  const redirectTo = location.state?.from?.pathname || ROUTES.MAIN_PAGE_PATH;
возможно стоит назвать как-то redirectUrl

2023-03-13 13:07 UTC, bondarevalexur commented on packages/client/src/core/Router/ProtectedRouteWrap.tsx
> +        to={location.state?.from?.pathname || ROUTES.MAIN_PAGE_PATH}
мб вынести это в .env

2023-03-13 14:40 UTC, Bluorenge commented
Зачем RequireAuthRout: пользователь вводит адрес, например, форума, -> проверка, залогинен ли он -> если нет, то перебрасывает на логин -> при сабмите, его возвращает на предыдущую страницу.

В лоадере нельзя использовать useLocation, а в компоненте можно. Этот хук нужен, чтобы можно было записать роут в историю.

2023-03-14 13:19 UTC, merged