Темизация
star-wars-kittens/The-star-wars-game pull request #30
Opened 2023-04-15 13:45 UTC by Winterstein9

### Какую задачу решаем
sta-29-themization
Добавление / изменение темы. Изменение темы доступно в профиле. Тема автоматически устанавливается в соответствии с темой устройства пользователя.
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-15 18:55 UTC, Bluorenge requested changes

2023-04-15 18:55 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/index.tsx
> +    console.log('hello');
консоль забыл убрать)

2023-04-15 18:55 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.scss
> +#theme__button {
почему по айди обращаешься?
и ещё у нас в проекте именование по бэму такое - сущностьКчемуОтносится, в данном случае btnTheme.

2023-04-15 19:38 UTC, Winterstein9 commented on packages/client/src/components/ThemeButton/ThemeButton.scss
> +#theme__button {
> почему по айди обращаешься? и ещё у нас в проекте именование по бэму такое - сущностьКчемуОтносится, в данном случае btnTheme.

id если стиль применяется к одному элементу, class если к более чем одному ...

2023-04-16 11:19 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.scss
> +#theme__button {
Во-первых, у нас на проекте используются классы.
Во-вторых, проблема с уникальностью селектора решается css-модулями (но мы их почему-то сразу не использовали).

2023-04-16 11:25 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/index.tsx
> +import './ThemeButton.scss';
смотри как у нас юзаются компоненты - в index находится только экспорт

2023-04-16 11:27 UTC, Bluorenge commented on packages/client/src/hooks/useTheme.ts
> +  return { theme, setTheme };
опять же ради единообразия (как в useLocale) давай как массив возвращать значения

2023-04-16 11:27 UTC, Bluorenge commented on packages/client/src/hooks/useTheme.ts
> +  return { theme, setTheme };
да и дефолтные хуки реакта (юсСтейт) тоже как массив же

2023-04-16 11:29 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.scss
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
зачем здесь семейство шрифта?

2023-04-16 11:32 UTC, Bluorenge commented on packages/client/src/components/Profile/ProfileForm/ProfileForm.tsx
> +        <ThemeButton />
Это надо было сразу обсудить, но может в хедер добавим смену темы? Рядом со сменой языка.

К тому же то, что она здесь путает - кнопка находится рядом со ссылками на другие страницы и ожидание, что это тоже ссылка на какую-то страницу смены темы.

2023-04-16 11:33 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/index.tsx
> +      value="Изменить тему"
Сюда бы переводы добавить сразу. Как это сделать можно посмотреть в других компонентах.

2023-04-16 13:44 UTC, Winterstein9 commented on packages/client/src/components/ThemeButton/index.tsx
> +import './ThemeButton.scss';
> смотри как у нас юзаются компоненты - в index находится только экспорт

Для чего так делать?

2023-04-16 13:47 UTC, Winterstein9 commented on packages/client/src/components/ThemeButton/ThemeButton.scss
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
> зачем здесь семейство шрифта?

 Иначе кнопка будет Times New Roman По другому нужно подключить? Как?

2023-04-17 08:18 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/index.tsx
> +import './ThemeButton.scss';
для единообразия

2023-04-17 08:20 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.scss
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
вообще надо было использовать компонент button из antd

2023-04-17 08:23 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.scss
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
а вдруг семейство шрифтов изменится? можно забыть поменять здесь шрифт

2023-04-17 08:24 UTC, Bluorenge commented on packages/client/src/components/Profile/ProfileForm/ProfileForm.tsx
> +        <ThemeButton />
Что скажешь? Сейчас эта кнопка как ссылка неочевидна для пользователя

2023-04-17 08:24 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/index.tsx
> +      value="Изменить тему"
переводы решил не делать?

2023-04-17 08:29 UTC, Winterstein9 commented on packages/client/src/components/Profile/ProfileForm/ProfileForm.tsx
> +        <ThemeButton />
> Что скажешь? Сейчас эта кнопка как ссылка неочевидна для пользователя

переделываю... фактически готово, но мешают ошибки отображения сайта ... наверное нужно браузер почистить

2023-04-17 12:52 UTC, Bluorenge commented on .hintrc
> +{
а этот файл зачем? я просто не в теме)

2023-04-17 12:52 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.tsx
> +    <label className="switch">
окей, можно и так, но смотри, есть же свитчер в анте - https://ant.design/components/switch

2023-04-17 12:56 UTC, Winterstein9 commented on .hintrc
> +{
> а этот файл зачем? я просто не в теме)

иначе ошибка отсутвия label хотя label есть и связь с input не меняет ситуации.

2023-04-17 13:02 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.tsx
> +        value="light"
сюда надо передать theme, чтобы react ошибку не кидал в консоль https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable

2023-04-17 13:05 UTC, Bluorenge commented on packages/client/src/components/ThemeButton/ThemeButton.tsx
> +  const themeSwitcher = (e: any) => {
Лучше типизировать, чтобы ворнинга линтера не было. Передаём HTMLInputElement. Но тогда ниже нужно передавать e.currentTarget. Ну и аргумент тогда должен быть назван не e, а как-нибудь inputEl, потому что мы же не к событию обращаемся, а вызываем метод на элементе.

2023-04-17 13:09 UTC, Bluorenge commented on packages/client/src/hooks/useTheme.ts
> +  const defaultTheme = isDark.matches ? 'dark' : 'light';
почему бы не типизировать? сделай по аналогии с useLocale. Там типизирован язык - есть импорт файла app.d.ts

2023-04-17 13:12 UTC, Bluorenge commented on packages/client/src/hooks/useTheme.ts
> +  useLayoutEffect(() => {
почему здесь useLayoutEffect? react не рекодмендует его использовать https://react.dev/reference/react/useLayoutEffect

2023-04-17 13:15 UTC, Bluorenge commented on .hintrc
> +{
![image](https://user-images.githubusercontent.com/16067434/232495000-9af39ab9-369b-4d13-ac8a-3917bb1120df.png)
хм. у меня всё норм

2023-04-17 13:17 UTC, Bluorenge commented on packages/client/src/hooks/useTheme.ts
> +    localStorage.getItem('app-theme') || defaultTheme
по аналогии с useLocale выдели app-theme в константу

2023-04-17 13:18 UTC, Bluorenge commented on packages/client/src/hooks/useTheme.ts
> +    localStorage.getItem('app-theme') || defaultTheme
и камелКейсом её сделай, чтобы было единообразно

2023-04-18 07:10 UTC, Bluorenge approved these changes

2023-04-18 08:23 UTC, practicum-maxim-zyryanov approved these changes
Approve, но небольшое замечание оставил, да и хотелось бы видеть в описании скрины, в остальном спасибо в том числе @Bluorenge за проведённое ревью, реализация стала заметно лучше.

2023-04-18 08:23 UTC, practicum-maxim-zyryanov commented on packages/client/src/hooks/useTheme.ts
> +  );
Хорошая идея использовать `'(prefers-color-scheme:dark)'` в качестве дефолтного значения

2023-04-18 08:23 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/ThemeButton/ThemeButton.tsx
> +  };
Даже в этом небольшом фрагменте видим множество `dark` и `light`. Сделать опечатку вроде `daek` или `ligth` достаточно просто, а вот отыскать проблему будет сложно. Поэтому не помешало бы вынести эти строки в константы например.

2023-04-18 11:08 UTC, merged