#3 adds login and registration pages
star-wars-kittens/The-star-wars-game pull request #4
Opened 2023-02-10 12:10 UTC by stvdent47

страница регистрации:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/48121921/218275842-4fbdbcbf-e432-4cba-8cbc-bfe042159804.png">
страница логина:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/48121921/218275857-277f2d42-3474-4e53-bf4e-7d1ac09c2cc8.png">

2023-02-11 13:53 UTC, practicum-maxim-zyryanov requested changes
Есть хорошие решения в коде, но на реальном проекте код не прошёл бы ревью: 
1. Нет нормального описания (а здесь ведь можно было даже скрины приложить)
2. Код решает разные задачи - кроме страницы авторизации и регистрации, здесь и рефакторинг, и изменение настроек (из-за которых в куче файлов точки с запятой ставятся) и т.д.
3. Пул-реквест состоит из всего одного коммита, есть подозрение, что в локальной ветке ситуация такая же. Хотя если бы задачи настройки, создания страницы и валидации решались бы в разных коммитах, то это позволило бы постфактум всё собрать как надо.
4. Нечитаемые импорты, которые далее будет сложно поддерживать
5. Использование console.log где нужно и где не нужно

Тем не менее, ничего критичного для учебного проекта не вижу, готов дать Approve, если  появится нормальное описание (со скринами и упоминанием того, что используется AntD), а в linear.app появятся задачи (1) на решение бага с валидацией и (2) на рефакторинг строк, чтобы избавиться от длинных импортов и упростить переключение языка (номера прошу скинуть в комментарии к пул-реквесту, сделаете их, когда команде будет удобно)

Но в следующий раз буду сразу разворачивать пул-реквесты, которые содержат код, который никак не относится к основной задаче (т.е. править настройки линтера в задаче про страницу логина - не нормально, но подключать библиотеки, которые впервые пригодились по задаче - допустимо)

2023-02-11 13:53 UTC, practicum-maxim-zyryanov commented on packages/client/src/constants/main.ts
> +export const API_URL = 'https://ya-praktikum.tech/api/v2';
Хорошее решение вынести адрес API

2023-02-11 13:53 UTC, practicum-maxim-zyryanov commented on packages/client/src/constants/routes.ts
> +};
Хорошее решение собрать отдельно роуты

2023-02-11 13:53 UTC, practicum-maxim-zyryanov commented on packages/client/src/constants/text/default.ts
> +export const REQUIRED_FIELD_ERROR = 'This field is required';
Не очень удачное решение выносить текстовые константы в отдельные файлы, это создаст сложности при смене языка. Здесь возможно стоило бы собрать все константы в общий глобальный объект, или описать всё в JSON, сохранив иерархичность (ex: lang.login.button). Хотя хорошо, что константы заведены, учитывая, что хотите позднее менять язык.

2023-02-11 13:53 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/Register/Register.tsx
> +} from 'constants/text/auth';
Если собрать всё в одном объекте, то не потребуется писать и эти длинные импорты

2023-02-11 13:53 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/Register/Register.tsx
> +      console.log({ response });
Не хорошо оставлять console.log в завершенном коде, исключение можно сделать только для ветки catch, но не здесь

2023-02-11 13:53 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/Register/Register.tsx
> +          ]}>
Валидация спокойно пропускает русский язык, а следовательно и невалидный адрес

2023-02-11 13:53 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/Register/Register.tsx
> +        </Form.Item>
Здесь валидация легко пропускает вообще любые буквы

2023-02-11 18:52 UTC, stvdent47 commented on packages/client/src/components/Register/Register.tsx
> +      console.log({ response });
`response` сейчас нигде не используется, чтобы он просто не болтался, кинул его в консоль

2023-02-11 18:52 UTC, stvdent47 commented on packages/client/src/constants/text/default.ts
> +export const REQUIRED_FIELD_ERROR = 'This field is required';
поправил

2023-02-11 18:52 UTC, stvdent47 commented on packages/client/src/components/Register/Register.tsx
> +} from 'constants/text/auth';
поправил

2023-02-11 18:52 UTC, stvdent47 commented on packages/client/src/components/Register/Register.tsx
> +          ]}>
поправил

2023-02-11 18:52 UTC, stvdent47 commented on packages/client/src/components/Register/Register.tsx
> +        </Form.Item>
поправил

2023-02-11 23:19 UTC, practicum-maxim-zyryanov requested changes
Хорошо, что все комментарии учтены. Но к решению всё ещё есть вопросы, а в код теперь закралась ошибка.

2023-02-11 23:19 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/Login/Login.tsx
> +        {en['auth.form.headgin.login']}
Использование объектов позволяет отловить ошибки на этапе статического анализа, а также упрощает набор за счёт автодополнения. Использование словарей таких преимуществ не несёт, поэтому лови опечатку.

2023-02-11 23:19 UTC, practicum-maxim-zyryanov commented on packages/client/src/components/Login/Login.tsx
> +import { en } from 'translations';
Импорт en решает проблему с огромными импортами, но не решает проблему поддержки. Если решите переключать на русский язык, то придётся везде менять объект на ru. В идеале должна быть возможность переключить язык вообще без перекомпиляции. 

К примеру, завести объект:
`let languages = {
   ru: {
      login: {
      ...
      }
   },
   en: {
      login {
     ...
      }
   }
}`

Тогда достаточно для пользователя хранить en/ru в localStorage и получать актуальные строки через что-нибудь вроде:
`let strings = languages[localStorage.getItem(LANG_KEY)]`
`<button>{strings.login.submit}</button>`

2023-02-12 08:04 UTC, stvdent47 commented on packages/client/src/components/Login/Login.tsx
> +        {en['auth.form.headgin.login']}
опечатка в json. с таким же успехом можно опечататься в названии объекта.
при использовании json так же работает автодополнение и подсвечиваются ошибки.

2023-02-12 08:06 UTC, stvdent47 commented on packages/client/src/components/Login/Login.tsx
> +import { en } from 'translations';
использование `en` прямо сейчас в коде — временное решение, дальше переключение языка отдадим какой-нибудь библиотеке типа react-intl, прямого взаимодействия с json-файлами в коде не будет

2023-02-12 08:33 UTC, practicum-maxim-zyryanov approved these changes

2023-02-12 12:45 UTC, podolskijspace commented
Добавь сообщения об успешной авторизации 
Предлагаю сделать валидацию на событие `blur`, вместо `change`, тогда не будет сообщений о неуспешном вводе постоянно
Если ты подключил локали, может стоит сразу вынести в отдельную задачи добавление библиотеки(чтобы не забыть и оперативно сделать), так как сейчас всп импорты идут с en, либо ru, потом их менять долго будет
Поле с repassword (там в примере анта есть как правильно валидировать, можно прям их код использовать, чтобы они зависимы были друг от друга)
Не обязательно, но будет круто, если добавишь информацию, что пользователь авторизовался в localstorage

2023-02-12 12:45 UTC, podolskijspace approved these changes

2023-02-12 13:24 UTC, stvdent47 commented
> Добавь сообщения об успешной авторизации

история же не про логику, а про создание страниц, наверно я чуть вылез за задачу, когда сделал запросы уже. создал задачу для логики, ее будет смысл делать, когда будет redux, хранить стейт `isLoggedIn` в localStorage — такая себе практика, как мне кажется, пользователь сможет вручную поменять получается.
и не понимаю, какой смысл делать оповещение об успешном логине, если тебя кинет на защищенный роут главной страницы, понятно же, что успешно, зачем еще показывать, что успешно. либо делать задержку, показывать оповещение, кидать на главную, что мне кажется излишним.
возможно, есть смысл сделать оповещение об успешной регистрации.

> Предлагаю сделать валидацию на событие blur, вместо change, тогда не будет сообщений о неуспешном вводе постоянно

получается, мне, чтобы узнать, что поле невалидно, нужно будет убрать с него фокус? не понимаю, зачем так делать мне кажется, это неудобно для пользователя. в этом, возможно, был бы смысл, если бы для валидации использовались сложные вычисление или запросы в бэк или еще куда, хотя в этом случае логичнее сделать через debounce.

> Если ты подключил локали, может стоит сразу вынести в отдельную задачи добавление библиотеки(чтобы не забыть и оперативно сделать), так как сейчас всп импорты идут с en, либо ru, потом их менять долго будет

создал задачу

> Поле с repassword (там в примере анта есть как правильно валидировать, можно прям их код использовать, чтобы они зависимы были друг от друга)
зачем нам это поле?

2023-02-12 13:26 UTC, merged