#7 create page leaderboard
star-wars-kittens/The-star-wars-game pull request #9
Opened 2023-02-21 17:39 UTC by podolskijspace

### Какую задачу решаем
Сделал страницу лидербордов

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/53047646/220419488-29bfc719-fa89-46f5-9335-8d41a742be44.png)

### TBD (если есть)

2023-02-21 21:04 UTC, stvdent47 requested changes
мне кажется, что про переменные для колонок не критично, но желательно, а вот про порядок в `en.json` мне кажется важным

2023-02-21 21:04 UTC, stvdent47 commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +    title: 'Имя',
мне кажется, было бы хорошо вынести в `en.json`
пока мы не делаем локализацию не критично, но, когда займемся, это может выстрелить нам в ногу и мы забудем, что здесь нужно тоже поменять, потому что искать, где нужно менять, будем через поиск

2023-02-21 21:04 UTC, stvdent47 commented on packages/client/src/translations/locales/en.json
> +  "leaderboard.title": "Leaderboard"
чтобы в дальнейшем было удобно искать, предлагаю располагать в алфавитном порядке

2023-02-22 13:46 UTC, podolskijspace commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +    title: 'Имя',
Хотел это сделать сразу, забыл, исправил

2023-02-22 13:46 UTC, podolskijspace commented on packages/client/src/translations/locales/en.json
> +  "leaderboard.title": "Leaderboard"
Поправил

2023-02-22 13:47 UTC, stvdent47 approved these changes

2023-02-22 15:27 UTC, practicum-maxim-zyryanov approved these changes

2023-03-03 18:44 UTC, merged